
name: Fix Bug

on:
  workflow_dispatch:
    inputs:
      commit_count:
        description: 'Number of commits to make'
        required: false
        default: '30'
        type: string

jobs:
  make-thirty-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Set up project structure
        run: |
          # Create realistic project structure
          mkdir -p src components utils tests docs assets
          
          # Create initial files if they don't exist
          if [ ! -f README.md ]; then
            cat > README.md << 'EOF'
          # Development Project
          
          This project demonstrates active development with regular commits and improvements.
          
          ## Features
          - Modern JavaScript architecture
          - Component-based structure
          - Comprehensive testing
          - Documentation
          
          ## Recent Activity Log
          EOF
          fi
          
          if [ ! -f package.json ]; then
            cat > package.json << 'EOF'
          {
            "name": "active-development",
            "version": "1.0.0",
            "description": "An actively developed project",
            "main": "src/index.js",
            "scripts": {
              "start": "node src/index.js",
              "test": "jest",
              "build": "webpack --mode=production",
              "dev": "webpack serve --mode=development"
            },
            "devDependencies": {
              "jest": "^29.0.0",
              "webpack": "^5.0.0"
            }
          }
          EOF
          fi
          
          if [ ! -f src/index.js ]; then
            cat > src/index.js << 'EOF'
          // Main application entry point
          console.log('Application starting...');
          // Core functionality will be added here
          function main() {
              console.log('Welcome to the application!');
          }
          main();
          EOF
          fi
      - name: Make 30 commits with realistic timing
        run: |
          TOTAL_COMMITS=${{ github.event.inputs.commit_count || '30' }}
          
          # Arrays of realistic commit messages
          declare -a messages=(
            "Add user authentication system"
            "Fix memory leak in data processing"
            "Implement responsive navigation menu"
            "Update dependencies to latest versions"
            "Add comprehensive error handling"
            "Optimize database query performance"
            "Create user profile management"
            "Fix CSS styling issues on mobile"
            "Add input validation for forms"
            "Implement search functionality"
            "Update documentation for API"
            "Add unit tests for core functions"
            "Fix typo in error messages"
            "Improve code readability and structure"
            "Add loading states for async operations"
            "Implement dark mode toggle"
            "Fix null pointer exceptions"
            "Add internationalization support"
            "Optimize image loading performance"
            "Create admin dashboard interface"
            "Add email notification system"
            "Fix broken links in navigation"
            "Implement data export feature"
            "Add comprehensive logging system"
            "Update README with examples"
            "Fix race condition in async code"
            "Add password strength validation"
            "Implement file upload functionality"
            "Create responsive grid layout"
            "Add social media integration"
            "Fix cross-browser compatibility issues"
            "Implement caching mechanism"
            "Add accessibility improvements"
            "Create automated testing pipeline"
            "Fix security vulnerabilities"
            "Add progress indicators"
            "Implement real-time notifications"
            "Create backup and restore system"
            "Add multi-language support"
            "Fix performance bottlenecks"
            "Implement lazy loading"
            "Add keyboard navigation support"
            "Create analytics dashboard"
            "Fix memory management issues"
            "Add offline mode support"
            "Implement drag and drop interface"
            "Create responsive image gallery"
            "Add webhook integration"
            "Fix timezone handling"
            "Implement rate limiting"
          )
          
          declare -a prefixes=(
            "feat: "
            "fix: "
            "refactor: "
            "docs: "
            "style: "
            "test: "
            "chore: "
            "perf: "
          )
          
          declare -a file_types=(
            "js"
            "css"
            "html"
            "json"
            "md"
            "test.js"
          )
          
          echo "Starting to make $TOTAL_COMMITS commits..."
          
          for i in $(seq 1 $TOTAL_COMMITS); do
            echo "Making commit $i of $TOTAL_COMMITS"
            
            # Choose random message and prefix
            msg_index=$((RANDOM % ${#messages[@]}))
            prefix_index=$((RANDOM % ${#prefixes[@]}))
            file_type_index=$((RANDOM % ${#file_types[@]}))
            
            message="${prefixes[$prefix_index]}${messages[$msg_index]}"
            file_ext="${file_types[$file_type_index]}"
            
            # Create realistic file changes based on commit type
            case "${prefixes[$prefix_index]}" in
              "feat: ")
                # Feature: Add to src directory
                echo "// Feature added on $(date)" >> "src/feature_$i.$file_ext"
                echo "- $(date): ${messages[$msg_index]}" >> README.md
                ;;
              "fix: ")
                # Bug fix: Modify existing files
                echo "// Bug fixed on $(date)" >> src/index.js
                ;;
              "refactor: ")
                # Refactor: Update components
                echo "// Code refactored on $(date)" >> "components/component_$i.js"
                ;;
              "docs: ")
                # Documentation: Update README or create docs
                echo "## Documentation Update $(date)" >> "docs/update_$i.md"
                echo "- Documentation updated: ${messages[$msg_index]}" >> README.md
                ;;
              "style: ")
                # Style: Create CSS files
                echo "/* Styling update $(date) */" >> "assets/style_$i.css"
                ;;
              "test: ")
                # Test: Add test files
                echo "// Test added on $(date)" >> "tests/test_$i.js"
                ;;
              "chore: ")
                # Chore: Update config files
                if [ -f package.json ]; then
                  # Update version number
                  sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"1.0.$i\"/" package.json
                fi
                ;;
              "perf: ")
                # Performance: Update utils
                echo "// Performance improvement $(date)" >> "utils/perf_$i.js"
                ;;
            esac
            
            # Stage all changes
            git add .
            
            # Make the commit
            git commit -m "$message"
            
            echo "✓ Committed: $message"
            
            # Realistic delay between commits (30 seconds to 3 minutes)
            if [ $i -lt $TOTAL_COMMITS ]; then
              delay=$((RANDOM % 150 + 30))
              echo "Waiting ${delay}s before next commit..."
              sleep $delay
            fi
          done
          
          echo "All $TOTAL_COMMITS commits completed!"
      - name: Push all changes
        run: |
          echo "Pushing all commits to repository..."
          git push origin main || git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "🎉 Successfully created ${{ github.event.inputs.commit_count || '30' }} commits!"
          echo "📊 Repository activity updated"
          echo "✅ All changes pushed to main branch"
